Доделать микросервис interests
apmath-web/interests pull request #41
Opened 2019-05-31 10:47 UTC by varlogen

- [ ]     Дописать микросервис
- [ ]     Добиться его работоспособности

close #40

2019-05-31 19:52 UTC, malinink requested changes

2019-05-31 19:52 UTC, malinink commented on Application/actions/actions.go
> +	service := services.CalculationService{}
все сервисы должна попадать друг в друга через конструктор!
правлять процессом должен SM
получать сервис в экшене - через SM.

2019-05-31 20:18 UTC, varlogen commented on Application/actions/actions.go
> +	service := services.CalculationService{}
Так это сервис доменного слоя. Я думаю правильно использовать менеджер только для сервайсов инфрастуктрного уровня

2019-06-01 07:46 UTC, malinink approved these changes

2019-06-01 07:47 UTC, merged